# Generated by Django 3.1.3 on 2020-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
