# Generated by Django 3.1.6 on 2021-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=120)),
                ('ingradiantnts', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('recipe_img', models.ImageField(upload_to='images')),
                ('created_by', models.CharField(max_length=120)),
            ],
        ),
    ]
