# Generated by Django 3.1.3 on 2020-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(max_length=120),
        ),
    ]
